--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: access_point; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.access_point (
    id bigint NOT NULL,
    ap_name character varying(255) NOT NULL,
    bridge_mode boolean NOT NULL,
    description character varying(255),
    ip_address character varying(255),
    mac_address character varying(255),
    model character varying(255),
    online boolean NOT NULL,
    school_name character varying(255),
    hotspot_id bigint NOT NULL
);


ALTER TABLE public.access_point OWNER TO postgres;

--
-- Name: access_point_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.access_point ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.access_point_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bridge_configurations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bridge_configurations (
    id bigint NOT NULL,
    bridge_name character varying(255),
    cidr character varying(255),
    configured boolean NOT NULL,
    description character varying(255),
    dhcp_pool_name character varying(255),
    dhcp_pool_range character varying(255),
    network_cidr character varying(255),
    subnet_mask integer NOT NULL,
    school_id bigint
);


ALTER TABLE public.bridge_configurations OWNER TO postgres;

--
-- Name: bridge_configurations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bridge_configurations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bridge_configurations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bridge_interfaces; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bridge_interfaces (
    bridge_id bigint NOT NULL,
    interface_name character varying(255)
);


ALTER TABLE public.bridge_interfaces OWNER TO postgres;

--
-- Name: devices; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.devices (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    device_name character varying(255) NOT NULL,
    mac_address character varying(255) NOT NULL,
    school_id bigint NOT NULL
);


ALTER TABLE public.devices OWNER TO postgres;

--
-- Name: devices_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotspot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hotspot (
    id bigint NOT NULL,
    configured boolean NOT NULL,
    configured_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    hotspot_name character varying(255) NOT NULL,
    interface_name character varying(255) NOT NULL,
    bridge_configuration_id bigint,
    port_configuration_id bigint,
    profile_id bigint NOT NULL
);


ALTER TABLE public.hotspot OWNER TO postgres;

--
-- Name: hotspot_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hotspot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotspot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotspot_users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hotspot_users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    expires_at timestamp(6) without time zone,
    mac_address character varying(255),
    password character varying(255) NOT NULL,
    profile_name character varying(255) NOT NULL,
    starts_at timestamp(6) without time zone,
    username character varying(255) NOT NULL,
    payment_transaction_id bigint NOT NULL
);


ALTER TABLE public.hotspot_users OWNER TO postgres;

--
-- Name: hotspot_users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hotspot_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotspot_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_intents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_intents (
    id bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    checkout_request_id character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    mac_address character varying(255),
    merchant_request_id character varying(255),
    phone_number character varying(255) NOT NULL,
    profile_id bigint NOT NULL,
    profile_name character varying(255) NOT NULL,
    status character varying(255),
    payment_transaction_id bigint,
    CONSTRAINT payment_intents_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'PROVISIONING'::character varying, 'READY'::character varying, 'FAILED'::character varying, 'STK_ACCEPTED'::character varying])::text[])))
);


ALTER TABLE public.payment_intents OWNER TO postgres;

--
-- Name: payment_intents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment_intents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_intents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_transactions (
    id bigint NOT NULL,
    amount numeric(38,2),
    checkout_request_id character varying(255),
    merchant_request_id character varying(255),
    mpesa_receipt_number character varying(255),
    paid_at timestamp(6) without time zone,
    phone_number character varying(255),
    profile_id bigint,
    profile_name character varying(255),
    raw_callback text,
    status character varying(255),
    CONSTRAINT payment_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'PROVISIONING'::character varying, 'READY'::character varying, 'FAILED'::character varying, 'STK_ACCEPTED'::character varying])::text[])))
);


ALTER TABLE public.payment_transactions OWNER TO postgres;

--
-- Name: payment_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: port_configuration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.port_configuration (
    id bigint NOT NULL,
    cidr character varying(255),
    configured boolean NOT NULL,
    configured_at timestamp(6) without time zone,
    description character varying(255),
    dhcp_pool_name character varying(255),
    dhcp_pool_range character varying(255),
    network_cidr character varying(255),
    port_name character varying(255),
    school_name character varying(255),
    subnet_mask integer NOT NULL,
    school_id bigint
);


ALTER TABLE public.port_configuration OWNER TO postgres;

--
-- Name: port_configuration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.port_configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.port_configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.school (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(255),
    location character varying(255),
    name character varying(255)
);


ALTER TABLE public.school OWNER TO postgres;

--
-- Name: school_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.school_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.school_seq OWNER TO postgres;

--
-- Name: server_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.server_profile (
    id bigint NOT NULL,
    configured boolean NOT NULL,
    created_at timestamp(6) without time zone,
    dns_name character varying(255) NOT NULL,
    hotspot_address character varying(255) NOT NULL,
    profile_name character varying(255) NOT NULL,
    bridge_configuration_id bigint NOT NULL
);


ALTER TABLE public.server_profile OWNER TO postgres;

--
-- Name: server_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.server_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.server_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_profile (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    description character varying(255),
    idle_timeout character varying(255),
    profile_name character varying(255) NOT NULL,
    rate_limit_download integer NOT NULL,
    rate_limit_upload integer NOT NULL,
    session_timeout character varying(255)
);


ALTER TABLE public.user_profile OWNER TO postgres;

--
-- Name: user_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255),
    updated_at timestamp(6) without time zone,
    username character varying(255) NOT NULL,
    school_id bigint,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ISP_ADMIN'::character varying, 'SCHOOL_ADMIN'::character varying, 'IT_SUPPORT'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wlan_configuration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wlan_configuration (
    id bigint NOT NULL,
    configured boolean NOT NULL,
    ssid_name character varying(255),
    wlan_interface character varying(255),
    school_id bigint
);


ALTER TABLE public.wlan_configuration OWNER TO postgres;

--
-- Name: wlan_configuration_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.wlan_configuration_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wlan_configuration_seq OWNER TO postgres;

--
-- Data for Name: access_point; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.access_point (id, ap_name, bridge_mode, description, ip_address, mac_address, model, online, school_name, hotspot_id) FROM stdin;
\.


--
-- Data for Name: bridge_configurations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bridge_configurations (id, bridge_name, cidr, configured, description, dhcp_pool_name, dhcp_pool_range, network_cidr, subnet_mask, school_id) FROM stdin;
3	bridge-huggin-high-school-lan-67844a	10.10.1.1/24	t	Bridge for Huggin High School	pool_bridge-huggin-high-school-lan-67844a_28f7c9	10.10.1.2-10.10.1.254	10.10.1.0/24	24	1
\.


--
-- Data for Name: bridge_interfaces; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bridge_interfaces (bridge_id, interface_name) FROM stdin;
3	wlan1
3	ether3
\.


--
-- Data for Name: devices; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.devices (id, created_at, device_name, mac_address, school_id) FROM stdin;
1	2025-12-19 00:50:02.275768	Tablet-Classroom-01	A1:B2:C3:D4:E5:F6	1
2	2025-12-19 00:52:26.332295	Tablet-Classroom-02	A1:B2:C3:D6:E7:F8	1
3	2025-12-19 00:59:21.930671	Tablet-Classroom-03	A1:B2:C3:D6:E7:F4	1
4	2025-12-19 01:02:36.34649	Tablet-classsrom-2	Q1:W2:E3:R4;T5:Y6	1
5	2025-12-19 01:02:50.495063	Tablet-classsrom-2	Q1:W2:E3:R4;T5:Y9	1
6	2025-12-19 01:11:14.052278	Tablet-classsrom-2	Q1:W2:E6:R4;T5:Y6	1
7	2025-12-23 22:12:37.090429	Tablet-classsrom-78	Q1:W2:E3:R4;T5:E1	1
8	2025-12-23 22:13:09.731275	Tablet-classsrom-290	Q1:W2:E3:Q7:T5:Y6	1
\.


--
-- Data for Name: hotspot; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.hotspot (id, configured, configured_at, created_at, hotspot_name, interface_name, bridge_configuration_id, port_configuration_id, profile_id) FROM stdin;
1	t	2025-12-24 00:49:56.910114	2025-12-24 00:49:56.910114	huggin-hight-hs	bridge-huggin-high-school-lan-67844a	3	\N	1
\.


--
-- Data for Name: hotspot_users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.hotspot_users (id, active, expires_at, mac_address, password, profile_name, starts_at, username, payment_transaction_id) FROM stdin;
\.


--
-- Data for Name: payment_intents; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payment_intents (id, amount, checkout_request_id, created_at, mac_address, merchant_request_id, phone_number, profile_id, profile_name, status, payment_transaction_id) FROM stdin;
\.


--
-- Data for Name: payment_transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payment_transactions (id, amount, checkout_request_id, merchant_request_id, mpesa_receipt_number, paid_at, phone_number, profile_id, profile_name, raw_callback, status) FROM stdin;
\.


--
-- Data for Name: port_configuration; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.port_configuration (id, cidr, configured, configured_at, description, dhcp_pool_name, dhcp_pool_range, network_cidr, port_name, school_name, subnet_mask, school_id) FROM stdin;
\.


--
-- Data for Name: school; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.school (id, active, code, location, name) FROM stdin;
1	t	SCH-DC3EB8C6	Ruaka,Nairobi	Huggin High School
\.


--
-- Data for Name: server_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.server_profile (id, configured, created_at, dns_name, hotspot_address, profile_name, bridge_configuration_id) FROM stdin;
1	t	2025-12-21 22:56:45.859051	huggin.wifi	10.10.1.1	hs-huggin-high-school-server	3
\.


--
-- Data for Name: user_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_profile (id, amount, description, idle_timeout, profile_name, rate_limit_download, rate_limit_upload, session_timeout) FROM stdin;
1	10.00	\N	10m	10 Mbps for 2 hours	10240	10240	2h
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, email, first_name, last_name, password, role, updated_at, username, school_id) FROM stdin;
1	2025-12-19 00:16:15.598289	admin@example.com	System	Admin	$2a$10$Sxe4h6ntrW0AOrK79GfdKOKMKMpNtEfJVd9/u74MwFUkHvgTx/63W	ISP_ADMIN	\N	admin	\N
2	2025-12-19 00:45:04.078987	buter@gmail.com	Mike	Buter	$2a$10$Gipt8/GwX3kW6tWDBMUPNOgJusbhoRrVQAlreRmNo4q7.7a2RP8v2	SCHOOL_ADMIN	\N	Mike Buter	1
3	2025-12-19 00:45:44.223284	kibe@gmail.com	Andrew	Kibe	$2a$10$TqbsVpufAlKQvzFrKc/K4ufyqIOikaVm2M75686GChbvFjwPTA2MO	IT_SUPPORT	\N	Andrew Kibe	1
4	2025-12-23 22:39:21.394426	ancient.snipe.zlsv@letterguard.net	Antony	Owuor	$2a$10$feirTBBnC4Umsp5JaaS4FeSLlCKYcxSnP18zvzgmK90hGNrsKPEKC	IT_SUPPORT	\N	Antony	1
\.


--
-- Data for Name: wlan_configuration; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.wlan_configuration (id, configured, ssid_name, wlan_interface, school_id) FROM stdin;
1	t	Somolink Wifi	wlan1	1
\.


--
-- Name: access_point_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.access_point_id_seq', 1, false);


--
-- Name: bridge_configurations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bridge_configurations_id_seq', 3, true);


--
-- Name: devices_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.devices_id_seq', 8, true);


--
-- Name: hotspot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hotspot_id_seq', 1, true);


--
-- Name: hotspot_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hotspot_users_id_seq', 1, false);


--
-- Name: payment_intents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payment_intents_id_seq', 1, false);


--
-- Name: payment_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payment_transactions_id_seq', 1, false);


--
-- Name: port_configuration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.port_configuration_id_seq', 1, false);


--
-- Name: school_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.school_seq', 1, true);


--
-- Name: server_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.server_profile_id_seq', 1, true);


--
-- Name: user_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_profile_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- Name: wlan_configuration_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.wlan_configuration_seq', 1, true);


--
-- Name: access_point access_point_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access_point
    ADD CONSTRAINT access_point_pkey PRIMARY KEY (id);


--
-- Name: bridge_configurations bridge_configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bridge_configurations
    ADD CONSTRAINT bridge_configurations_pkey PRIMARY KEY (id);


--
-- Name: devices devices_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT devices_pkey PRIMARY KEY (id);


--
-- Name: hotspot hotspot_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot
    ADD CONSTRAINT hotspot_pkey PRIMARY KEY (id);


--
-- Name: hotspot_users hotspot_users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot_users
    ADD CONSTRAINT hotspot_users_pkey PRIMARY KEY (id);


--
-- Name: payment_intents payment_intents_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_intents
    ADD CONSTRAINT payment_intents_pkey PRIMARY KEY (id);


--
-- Name: payment_transactions payment_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT payment_transactions_pkey PRIMARY KEY (id);


--
-- Name: port_configuration port_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.port_configuration
    ADD CONSTRAINT port_configuration_pkey PRIMARY KEY (id);


--
-- Name: school school_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.school
    ADD CONSTRAINT school_pkey PRIMARY KEY (id);


--
-- Name: server_profile server_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.server_profile
    ADD CONSTRAINT server_profile_pkey PRIMARY KEY (id);


--
-- Name: hotspot_users uk45c5bstc4t4fif9oiomkkj5yt; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot_users
    ADD CONSTRAINT uk45c5bstc4t4fif9oiomkkj5yt UNIQUE (username);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: user_profile uk9whbi9ti4cc9v7y527yge6k55; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT uk9whbi9ti4cc9v7y527yge6k55 UNIQUE (profile_name);


--
-- Name: server_profile ukaamthkfuin52wntku0cpbnpus; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.server_profile
    ADD CONSTRAINT ukaamthkfuin52wntku0cpbnpus UNIQUE (profile_name);


--
-- Name: devices ukbfdu66xgk53rkn5023ce70rvw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT ukbfdu66xgk53rkn5023ce70rvw UNIQUE (mac_address);


--
-- Name: hotspot ukj6pqlesk99afc9s3dpx1iohaa; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot
    ADD CONSTRAINT ukj6pqlesk99afc9s3dpx1iohaa UNIQUE (port_configuration_id);


--
-- Name: port_configuration ukjoyby40s1ks8te5n6g4ni3xvj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.port_configuration
    ADD CONSTRAINT ukjoyby40s1ks8te5n6g4ni3xvj UNIQUE (school_id);


--
-- Name: payment_intents ukkxbnhfdtbxp5gaijpabrjlbwg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_intents
    ADD CONSTRAINT ukkxbnhfdtbxp5gaijpabrjlbwg UNIQUE (payment_transaction_id);


--
-- Name: hotspot_users ukl2px20ao1kocsdg72qy96rkmb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot_users
    ADD CONSTRAINT ukl2px20ao1kocsdg72qy96rkmb UNIQUE (payment_transaction_id);


--
-- Name: payment_intents uklj0hd0d5b03eaxtj88f3pc3et; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_intents
    ADD CONSTRAINT uklj0hd0d5b03eaxtj88f3pc3et UNIQUE (checkout_request_id);


--
-- Name: server_profile ukme5af78qiyv7tiik5ohhhsn2b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.server_profile
    ADD CONSTRAINT ukme5af78qiyv7tiik5ohhhsn2b UNIQUE (bridge_configuration_id);


--
-- Name: bridge_configurations ukp5vlfntgk4q6xoy31943ilvk0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bridge_configurations
    ADD CONSTRAINT ukp5vlfntgk4q6xoy31943ilvk0 UNIQUE (school_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: hotspot ukwh9gs7s36ilb9sw5v96m1jmv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot
    ADD CONSTRAINT ukwh9gs7s36ilb9sw5v96m1jmv UNIQUE (bridge_configuration_id);


--
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: wlan_configuration wlan_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wlan_configuration
    ADD CONSTRAINT wlan_configuration_pkey PRIMARY KEY (id);


--
-- Name: devices fk1fpxteaqelig9f7hnt01jy4l0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.devices
    ADD CONSTRAINT fk1fpxteaqelig9f7hnt01jy4l0 FOREIGN KEY (school_id) REFERENCES public.school(id);


--
-- Name: bridge_configurations fk3dq4dim8jk53u2y0boms2reff; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bridge_configurations
    ADD CONSTRAINT fk3dq4dim8jk53u2y0boms2reff FOREIGN KEY (school_id) REFERENCES public.school(id);


--
-- Name: port_configuration fk588ivn5q3f79ye87og6blrjfq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.port_configuration
    ADD CONSTRAINT fk588ivn5q3f79ye87og6blrjfq FOREIGN KEY (school_id) REFERENCES public.school(id);


--
-- Name: hotspot fk7dlmuhqi14fk77xc5ywu09a8m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot
    ADD CONSTRAINT fk7dlmuhqi14fk77xc5ywu09a8m FOREIGN KEY (bridge_configuration_id) REFERENCES public.bridge_configurations(id);


--
-- Name: hotspot fk8bndnreaxg3ehyp091k2kjff8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot
    ADD CONSTRAINT fk8bndnreaxg3ehyp091k2kjff8 FOREIGN KEY (profile_id) REFERENCES public.server_profile(id);


--
-- Name: bridge_interfaces fka6tppjqemqpwdqawfsol0uxiu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bridge_interfaces
    ADD CONSTRAINT fka6tppjqemqpwdqawfsol0uxiu FOREIGN KEY (bridge_id) REFERENCES public.bridge_configurations(id);


--
-- Name: users fkemivb8l5w3ax4ggsxnbdb3r45; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkemivb8l5w3ax4ggsxnbdb3r45 FOREIGN KEY (school_id) REFERENCES public.school(id);


--
-- Name: hotspot fkjialbbjikiwvjnmcmrso7frxj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot
    ADD CONSTRAINT fkjialbbjikiwvjnmcmrso7frxj FOREIGN KEY (port_configuration_id) REFERENCES public.port_configuration(id);


--
-- Name: payment_intents fkjj52ne8l8k11xdk960kj7791g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_intents
    ADD CONSTRAINT fkjj52ne8l8k11xdk960kj7791g FOREIGN KEY (payment_transaction_id) REFERENCES public.payment_transactions(id);


--
-- Name: server_profile fkl0mmi8tggt7md3h42euv6l80f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.server_profile
    ADD CONSTRAINT fkl0mmi8tggt7md3h42euv6l80f FOREIGN KEY (bridge_configuration_id) REFERENCES public.bridge_configurations(id);


--
-- Name: access_point fkpdd7aywwun0wc7c31b12b6nqx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access_point
    ADD CONSTRAINT fkpdd7aywwun0wc7c31b12b6nqx FOREIGN KEY (hotspot_id) REFERENCES public.hotspot(id);


--
-- Name: wlan_configuration fksgurtdpwvqd9kujnvcesd2w6q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wlan_configuration
    ADD CONSTRAINT fksgurtdpwvqd9kujnvcesd2w6q FOREIGN KEY (school_id) REFERENCES public.school(id);


--
-- Name: hotspot_users fkski9p5bh7kubbe3j3j5e1s6o3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hotspot_users
    ADD CONSTRAINT fkski9p5bh7kubbe3j3j5e1s6o3 FOREIGN KEY (payment_transaction_id) REFERENCES public.payment_transactions(id);


--
-- PostgreSQL database dump complete
--

